# Generated by Django 4.1.3 on 2023-05-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreg',
            name='whatsapp',
            field=models.BigIntegerField(),
        ),
    ]
